// All user-facing text. `{name}` placeholders are filled by context.tr().

class Strings {
  static const byLang = {'sq': sq, 'en': en};

  static const sq = <String, String>{
    // General
    'continue': 'Vazhdo',
    'save': 'Ruaj',
    'cancel': 'Anulo',
    'ok': 'Në rregull',
    'no': 'Jo',
    'apply': 'Apliko',
    'skip': 'Kalo',
    'submit': 'Dërgo',
    'now': 'Tani',
    'locating': 'Po gjejmë vendndodhjen…',
    'current_location': 'Vendndodhja aktuale',
    'n_trips': '{n} udhëtime',
    'n_seats': '{n} vende',
    'passenger': 'Pasagjer',
    'driver': 'Shoferi',
    'car': 'Makina',

    // Login
    'login_title': 'Mirë se vini!',
    'login_subtitle':
        'Shkruani numrin e telefonit. Do t\'ju dërgojmë një kod me SMS.',
    'login_terms': 'Duke vazhduar, pranoni Kushtet e Përdorimit dhe Politikën e Privatësisë.',
    'invalid_phone':
        'Shkruani një numër celulari të vlefshëm shqiptar (p.sh. 069 123 4567)',
    'demo_login_hint':
        'Version demo: shkruani çdo numër shqiptar dhe kodin {code}.',
    'otp_title': 'Shkruani kodin',
    'otp_subtitle': 'Kodi 6-shifror u dërgua në {phone}',
    'verify': 'Verifiko',
    'resend_in': 'Ridërgo kodin pas {s}s',
    'resend_code': 'Ridërgo kodin',
    'setup_title': 'Si quheni?',
    'setup_subtitle': 'Emri juaj u shfaqet shoferëve dhe pasagjerëve.',
    'full_name': 'Emri dhe mbiemri',
    'enter_name': 'Ju lutem shkruani emrin tuaj',
    'how_use_app': 'Si do ta përdorni aplikacionin?',
    'role_passenger': 'Dua të udhëtoj',
    'role_passenger_desc': 'Porosisni taksi kudo në Shqipëri',
    'role_driver': 'Jam shofer taksie',
    'role_driver_desc': 'Merrni klientë dhe fitoni më shumë',
    'get_started': 'Fillo',

    // Tabs
    'tab_home': 'Kryefaqja',
    'tab_bookings': 'Rezervimet',
    'tab_chat': 'Biseda',
    'tab_profile': 'Profili',
    'tab_drive': 'Puno',
    'tab_earnings': 'Fitimet',
    'tab_account': 'Llogaria',

    // Home
    'good_morning': 'Mirëmëngjes',
    'good_afternoon': 'Mirëdita',
    'good_evening': 'Mirëmbrëma',
    'where_to_go': 'Ku dëshironi të shkoni?',
    'home_place': 'Shtëpia',
    'work_place': 'Puna',
    'cat_standard': 'Standard',
    'cat_luxury': 'Luksoze',
    'cat_van': 'Furgon',
    'cat_standard_desc': 'Makina të zakonshme, deri në 4 pasagjerë',
    'cat_luxury_desc': 'Makina premium (Mercedes S, BMW 7, Audi A8)',
    'cat_van_desc': 'Deri në 7 pasagjerë ose shumë bagazhe',
    'from_per_km': 'nga {p}/km',
    'limited_offer': 'Ofertë e kufizuar',
    'promo_title': '{p}% zbritje për udhëtimin e parë',
    'promo_active': 'Kodi u aktivizua',
    'promo_applied': 'Zbritja {p}% u aplikua',
    'promo_invalid': 'Kodi nuk është i vlefshëm ose është përdorur',
    'available_cars': 'Makina të lira',
    'no_cars_nearby': 'Nuk ka makina afër për momentin. Provoni pas pak.',
    'book': 'Rezervo',

    // Where to
    'where_to': 'Ku po shkoni?',
    'pickup_from': 'Ku t\'ju marrim?',
    'set_home': 'Adresa e shtëpisë',
    'set_work': 'Adresa e punës',
    'search_place': 'Kërkoni vend ose adresë',
    'use_current_location': 'Përdor vendndodhjen aktuale',
    'saved_places': 'Vendet e ruajtura',
    'recent': 'Së fundmi',
    'suggested': 'Të sugjeruara',
    'no_results': 'Asnjë rezultat. Provoni një emër tjetër.',

    // Booking steps
    'step_route': 'Rruga',
    'step_payment': 'Pagesa',
    'step_car': 'Makina',
    'pickup_current': 'Nisja',
    'destination': 'Destinacioni',
    'min_drive': '~{m} rrugë',
    'continue_to_payment': 'Vazhdo te pagesa',
    'how_pay': 'Si dëshironi të paguani?',
    'charged_after': 'Paguani vetëm kur mbaron udhëtimi.',
    'pay_cash': 'Para në dorë',
    'pay_cash_desc': 'Paguani shoferin në fund të udhëtimit',
    'pay_card': 'Kartë',
    'cards': 'Kartat',
    'add_card': 'Shto kartë',
    'digital_wallets': 'Portofole dixhitale',
    'confirm_face_id': 'Konfirmo me Face ID',
    'confirm_google': 'Konfirmo me Google',
    'paying_with': 'Paguani me',
    'pay_with': 'Pagesa',
    'card_number': 'Numri i kartës',
    'card_invalid': 'Numri i kartës nuk është i saktë',
    'expiry_invalid': 'Data e skadencës duhet të jetë MM/VV',
    'card_expired': 'Kjo kartë ka skaduar',
    'cvc_invalid': 'Kodi CVC nuk është i saktë',
    'card_secure': 'Në telefon ruhen vetëm 4 shifrat e fundit të kartës.',
    'choose_car': 'Zgjidhni makinën',
    'fares_note':
        'Çmimet janë për këtë udhëtim. Shoferët mund të kërkojnë pak më shumë.',
    'car_types': 'Llojet e makinave',
    'n_nearby': '{n} afër',
    'your_offer': 'Oferta juaj',
    'night_tariff': 'Tarifa e natës (22:00–06:00) është +20%.',
    'find_driver': 'Gjej shofer',

    // Finding a driver
    'searching_nearby': 'Po kërkojmë afër…',
    'n_drivers_found': 'U gjetën {n} shoferë',
    'offer_from': 'Ofertë nga {name}',
    'looking_another': 'Po kërkojmë shofer tjetër…',
    'ride_confirmed': 'Udhëtimi u konfirmua',
    'finding_driver': 'Po gjejmë shoferin tuaj',
    'asking_drivers': 'Po pyesim shoferët {category} afër jush',
    'you_declined': 'Refuzuat ofertën e {name}',
    'your_fare': 'Çmimi juaj',
    'scanning_streets': 'Po skanojmë rrugët përreth jush',
    'n_drivers_waiting': '{n} shoferë afër, në pritje të përgjigjes',
    'cancel_search': 'Anulo kërkimin',
    'new_offer': 'Ofertë e re',
    'n_more_offers': '+{n} oferta',
    'min_away': '{m} larg',
    'driver_asks': '{name} kërkon',
    'your_price': 'Çmimi juaj',
    'decline': 'Refuzo',
    'accept': 'Prano',
    'driver_on_way_in': '{name} po vjen me {car}',
    'no_drivers_title': 'Asnjë shofer i lirë',
    'no_drivers_body':
        'Nuk gjetëm shofer këtë herë. Provoni përsëri ose rrisni pak ofertën.',

    // Ride
    'driver_on_way': 'Shoferi po vjen',
    'driver_arrived': 'Shoferi mbërriti',
    'on_trip': 'Në udhëtim',
    'arriving_soon': 'Po mbërrin së shpejti',
    'heading_to_you': '{name} po vjen drejt jush',
    'driver_here': 'Shoferi juaj është këtu!',
    'meet_at_pickup': 'Takoni {name} te pika e nisjes',
    'heading_to': 'Drejt {place}',
    'enjoy_ride': 'Udhëtim të mbarë me {name}!',
    'call': 'Telefono',
    'message': 'Mesazh',
    'share': 'Ndaj',
    'cannot_call': 'Telefonata nuk mund të kryhet nga kjo pajisje',
    'cancel_why': 'Pse po e anuloni?',
    'reason_too_far': 'Shoferi është shumë larg',
    'reason_changed_mind': 'Ndryshova mendje',
    'reason_driver_asked': 'Shoferi më kërkoi ta anuloj',
    'reason_other_ride': 'Gjeta mjet tjetër',
    'reason_other': 'Tjetër',
    'ride_cancelled': 'Udhëtimi u anulua',
    'ride_cancelled_body':
        'Shoferi e anuloi udhëtimin. Mund të porosisni një tjetër menjëherë.',
    'share_text': 'Jam në taksi me {driver} ({car}), drejt {to}. Mbërrij për rreth {eta}.',
    'copied_share':
        'Detajet e udhëtimit u kopjuan. Dërgojini dikujt që i besoni.',
    'safety': 'Siguria',
    'emergency': 'Emergjenca',
    'police': 'Policia',
    'ambulance': 'Ambulanca',
    'support': 'Ndihma',
    'you_arrived': 'Mbërritët!',
    'fare': 'Çmimi',
    'tip': 'Bakshish',
    'total': 'Totali',
    'payment': 'Pagesa',
    'distance': 'Distanca',
    'pay_driver_cash': 'Ju lutem paguani shoferin {amount} me para në dorë.',
    'rate_driver': 'Si ishte udhëtimi me {name}?',
    'add_tip': 'Shtoni bakshish (opsionale)',
    'no_tip': 'Pa bakshish',
    'comment_hint': 'Koment (opsional)',
    'thanks_rating': 'Faleminderit për vlerësimin!',

    // Chat
    'chat_empty': 'Dërgoni një mesazh te {name}',
    'type_message': 'Shkruani një mesazh…',
    'quick_coming': 'Po vij tani',
    'quick_where': 'Ku ndodheni saktësisht?',
    'quick_wait': 'Më prisni 2 minuta, ju lutem',
    'quick_thanks': 'Faleminderit!',
    'no_chats': 'Bisedat me shoferin shfaqen këtu gjatë udhëtimit.',
    'your_driver': 'Shoferi juaj',
    'support_team': 'Ekipi i {brand}',
    'support_desc': 'Na shkruani në WhatsApp, 7 ditë në javë',

    // Bookings
    'active_ride': 'Udhëtimi aktual',
    'past_rides': 'Udhëtimet e mëparshme',
    'no_rides': 'Ende nuk keni udhëtime.',
    'cancelled': 'Anuluar',
    'in_progress': 'Në vazhdim',
    'receipt': 'Fatura',
    'your_rating': 'Vlerësimi juaj',

    // Profile
    'payment_methods': 'Mënyrat e pagesës',
    'promo_code': 'Kodi promocional',
    'enter_code': 'Shkruani kodin',
    'settings': 'Cilësimet',
    'language': 'Gjuha',
    'terms_privacy': 'Kushtet & Privatësia',
    'legal_text':
        'Duke përdorur aplikacionin pranoni kushtet e përdorimit. '
        'Të dhënat tuaja përpunohen sipas ligjit shqiptar për mbrojtjen e të dhënave personale.',
    'sign_out': 'Dilni',
    'tap_to_set': 'Prekni për ta vendosur',
    'become_driver': 'Bëhu shofer',
    'become_driver_desc': 'Keni taksi? Filloni të merrni klientë',
    'switch_to_passenger': 'Kalo në modalitetin pasagjer',

    // Driver
    'you_are_online': 'Jeni online',
    'you_are_offline': 'Jeni offline',
    'n_requests': '{n} kërkesa',
    'go_online': 'Hyr online',
    'go_offline': 'Dil offline',
    'go_online_title': 'Gati për punë?',
    'go_online_desc': 'Hyni online për të marrë kërkesa nga pasagjerët afër.',
    'waiting_requests': 'Po presim kërkesa…',
    'waiting_requests_desc': 'Kërkesat e reja shfaqen këtu automatikisht.',
    'request_meta': '{eta} deri te klienti · udhëtim {km}, ~{min}',
    'offer_sent_waiting': 'Oferta {price} u dërgua. Po presim pasagjerin…',
    'accept_for': 'Prano për {price}',
    'passenger_chose_other': 'Pasagjeri zgjodhi një shofer tjetër',
    'go_to_pickup': 'Shko te klienti',
    'waiting_passenger': 'Në pritje të pasagjerit',
    'drive_to_destination': 'Drejt destinacionit',
    'navigate': 'Navigo',
    'i_arrived': 'Mbërrita',
    'start_trip': 'Fillo udhëtimin',
    'complete_trip': 'Përfundo udhëtimin',
    'trip_completed': 'Udhëtimi përfundoi',
    'collect_cash': 'Merrni {amount} para në dorë nga pasagjeri.',
    'paid_by_card': '{amount} paguhen me kartë.',
    'cancel_ride_q': 'Ta anuloni udhëtimin?',
    'cancel_ride_driver_warning': 'Anulimet e shpeshta ulin vlerësimin tuaj.',
    'yes_cancel': 'Po, anuloje',
    'today': 'Sot',
    'trips': 'Udhëtime',
    'online_hours': 'Orë online',
    'avg_trip': 'Mesatarja',
    'last_7_days': '7 ditët e fundit',
    'zero_commission': 'Pa komision: çdo lek i udhëtimit është i juaji.',
    'recent_trips': 'Udhëtimet e fundit',
    'no_trips_yet': 'Ende nuk keni udhëtime sot.',
    'your_vehicle': 'Makina juaj',
    'add_vehicle': 'Shtoni makinën',
    'vehicle_intro':
        'Pasagjerët shohin markën, modelin dhe targën para se të hipin.',
    'make': 'Marka',
    'model': 'Modeli',
    'plate': 'Targa',
    'color': 'Ngjyra',
    'service_type': 'Lloji i shërbimit',
    'fill_all_fields': 'Plotësoni markën dhe modelin',
    'invalid_plate': 'Targa duhet të jetë si AA 123 BB',
    'pending_approval': 'Dokumentet tuaja po shqyrtohen. Do të njoftoheni kur llogaria të aprovohet.',
    'documents': 'Dokumentet',
    'doc_license': 'Leja e drejtimit',
    'doc_registration': 'Leja e qarkullimit',
    'doc_taxi_permit': 'Licenca e taksisë (Bashkia)',
    'doc_insurance': 'Siguracioni i makinës',
    'doc_verified': 'Verifikuar',
    'doc_send_office': 'Dërgojeni në zyrë ose në WhatsApp',

    // Errors
    'err_generic': 'Diçka shkoi keq. Provoni përsëri.',
    'err_invalid_code': 'Kodi është i gabuar',
    'err_otp_expired': 'Kodi ka skaduar. Kërkoni një kod të ri.',
    'err_over_sms_send_rate_limit':
        'Shumë kërkesa. Prisni pak para se të kërkoni kod tjetër.',
    'err_sms_send_failed': 'SMS nuk u dërgua. Kontrolloni numrin.',
    'err_request_closed': 'Kjo kërkesë nuk është më aktive',
    'err_offer_expired': 'Oferta skadoi',
    'err_passenger_chose_another': 'Pasagjeri zgjodhi një shofer tjetër',
    'err_vehicle_not_approved': 'Makina juaj nuk është aprovuar ende',
    'err_wrong_category': 'Kjo kërkesë është për lloj tjetër makine',
    'err_driver_offline': 'Hyni online për të dërguar oferta',
    'err_subscription_expired': 'Abonimi juaj ka skaduar. Kontaktoni zyrën.',
    'err_price_too_low':
        'Çmimi nuk mund të jetë më i ulët se oferta e pasagjerit',
    'err_not_allowed': 'Ky veprim nuk lejohet',
    'err_driver_busy': 'Shoferi sapo mori një udhëtim tjetër',
    'err_cannot_cancel': 'Udhëtimi nuk mund të anulohet tani',
    'err_invalid_transition': 'Veprim i pavlefshëm për këtë udhëtim',
  };

  static const en = <String, String>{
    // General
    'continue': 'Continue',
    'save': 'Save',
    'cancel': 'Cancel',
    'ok': 'OK',
    'no': 'No',
    'apply': 'Apply',
    'skip': 'Skip',
    'submit': 'Submit',
    'now': 'Now',
    'locating': 'Finding your location…',
    'current_location': 'Current location',
    'n_trips': '{n} trips',
    'n_seats': '{n} seats',
    'passenger': 'Passenger',
    'driver': 'Driver',
    'car': 'Car',

    // Login
    'login_title': 'Welcome!',
    'login_subtitle': 'Enter your phone number. We will text you a code.',
    'login_terms':
        'By continuing you accept the Terms of Use and Privacy Policy.',
    'invalid_phone': 'Enter a valid Albanian mobile number (e.g. 069 123 4567)',
    'demo_login_hint':
        'Demo version: enter any Albanian number and the code {code}.',
    'otp_title': 'Enter the code',
    'otp_subtitle': 'We sent a 6-digit code to {phone}',
    'verify': 'Verify',
    'resend_in': 'Resend code in {s}s',
    'resend_code': 'Resend code',
    'setup_title': 'What is your name?',
    'setup_subtitle': 'Your name is shown to drivers and passengers.',
    'full_name': 'Full name',
    'enter_name': 'Please enter your name',
    'how_use_app': 'How will you use the app?',
    'role_passenger': 'I want to ride',
    'role_passenger_desc': 'Order a taxi anywhere in Albania',
    'role_driver': 'I drive a taxi',
    'role_driver_desc': 'Get customers and earn more',
    'get_started': 'Get started',

    // Tabs
    'tab_home': 'Home',
    'tab_bookings': 'Bookings',
    'tab_chat': 'Chat',
    'tab_profile': 'Profile',
    'tab_drive': 'Drive',
    'tab_earnings': 'Earnings',
    'tab_account': 'Account',

    // Home
    'good_morning': 'Good morning',
    'good_afternoon': 'Good afternoon',
    'good_evening': 'Good evening',
    'where_to_go': 'Where would you go?',
    'home_place': 'Home',
    'work_place': 'Work',
    'cat_standard': 'Standard',
    'cat_luxury': 'Luxury',
    'cat_van': 'Van',
    'cat_standard_desc': 'Everyday cars, up to 4 passengers',
    'cat_luxury_desc': 'Premium cars (Mercedes S, BMW 7, Audi A8)',
    'cat_van_desc': 'Up to 7 passengers or lots of luggage',
    'from_per_km': 'from {p}/km',
    'limited_offer': 'Limited offer',
    'promo_title': '{p}% off your first ride',
    'promo_active': 'Code applied',
    'promo_applied': '{p}% discount applied',
    'promo_invalid': 'This code is invalid or already used',
    'available_cars': 'Available cars',
    'no_cars_nearby': 'No cars nearby right now. Try again in a moment.',
    'book': 'Book',

    // Where to
    'where_to': 'Where to?',
    'pickup_from': 'Where should we pick you up?',
    'set_home': 'Home address',
    'set_work': 'Work address',
    'search_place': 'Search a place or address',
    'use_current_location': 'Use current location',
    'saved_places': 'Saved places',
    'recent': 'Recent',
    'suggested': 'Suggested',
    'no_results': 'No results. Try another name.',

    // Booking steps
    'step_route': 'Route',
    'step_payment': 'Payment',
    'step_car': 'Car',
    'pickup_current': 'Pick-up',
    'destination': 'Destination',
    'min_drive': '~{m} drive',
    'continue_to_payment': 'Continue to payment',
    'how_pay': 'How would you like to pay?',
    'charged_after': 'You are only charged once the ride ends.',
    'pay_cash': 'Cash',
    'pay_cash_desc': 'Pay the driver at the end of the ride',
    'pay_card': 'Card',
    'cards': 'Cards',
    'add_card': 'Add card',
    'digital_wallets': 'Digital wallets',
    'confirm_face_id': 'Confirm with Face ID',
    'confirm_google': 'Confirm with Google',
    'paying_with': 'Paying with',
    'pay_with': 'Pay with',
    'card_number': 'Card number',
    'card_invalid': 'The card number is not valid',
    'expiry_invalid': 'Expiry must be MM/YY',
    'card_expired': 'This card has expired',
    'cvc_invalid': 'The CVC is not valid',
    'card_secure':
        'Only the last 4 digits of the card are stored on the phone.',
    'choose_car': 'Choose your car',
    'fares_note': 'Fares are for this trip. Drivers may ask for a bit more.',
    'car_types': 'Car types',
    'n_nearby': '{n} nearby',
    'your_offer': 'Your offer',
    'night_tariff': 'Night tariff (22:00–06:00) is +20%.',
    'find_driver': 'Find driver',

    // Finding a driver
    'searching_nearby': 'Searching nearby…',
    'n_drivers_found': '{n} drivers found',
    'offer_from': 'Offer from {name}',
    'looking_another': 'Looking for another driver…',
    'ride_confirmed': 'Ride confirmed',
    'finding_driver': 'Finding your driver',
    'asking_drivers': 'Asking {category} drivers near you',
    'you_declined': 'You declined {name}\'s offer',
    'your_fare': 'Your fare',
    'scanning_streets': 'Scanning the streets around you',
    'n_drivers_waiting': '{n} drivers nearby, waiting for an answer',
    'cancel_search': 'Cancel search',
    'new_offer': 'New offer',
    'n_more_offers': '+{n} offers',
    'min_away': '{m} away',
    'driver_asks': '{name} asks',
    'your_price': 'Your price',
    'decline': 'Decline',
    'accept': 'Accept',
    'driver_on_way_in': '{name} is on the way in the {car}',
    'no_drivers_title': 'No drivers available',
    'no_drivers_body': 'We could not find a driver this time. Try again or raise your offer a little.',

    // Ride
    'driver_on_way': 'Driver on the way',
    'driver_arrived': 'Driver has arrived',
    'on_trip': 'On the trip',
    'arriving_soon': 'Arriving soon',
    'heading_to_you': '{name} is heading to you',
    'driver_here': 'Your driver is here!',
    'meet_at_pickup': 'Meet {name} at the pickup point',
    'heading_to': 'To {place}',
    'enjoy_ride': 'Enjoy your ride with {name}!',
    'call': 'Call',
    'message': 'Message',
    'share': 'Share',
    'cannot_call': 'Calls are not available on this device',
    'cancel_why': 'Why are you cancelling?',
    'reason_too_far': 'Driver is too far away',
    'reason_changed_mind': 'I changed my mind',
    'reason_driver_asked': 'Driver asked me to cancel',
    'reason_other_ride': 'I found another ride',
    'reason_other': 'Other',
    'ride_cancelled': 'Ride cancelled',
    'ride_cancelled_body':
        'The driver cancelled the ride. You can book another one right away.',
    'share_text': 'I\'m in a taxi with {driver} ({car}), going to {to}. Arriving in about {eta}.',
    'copied_share': 'Trip details copied. Send them to someone you trust.',
    'safety': 'Safety',
    'emergency': 'Emergency',
    'police': 'Police',
    'ambulance': 'Ambulance',
    'support': 'Support',
    'you_arrived': 'You have arrived!',
    'fare': 'Fare',
    'tip': 'Tip',
    'total': 'Total',
    'payment': 'Payment',
    'distance': 'Distance',
    'pay_driver_cash': 'Please pay the driver {amount} in cash.',
    'rate_driver': 'How was your ride with {name}?',
    'add_tip': 'Add a tip (optional)',
    'no_tip': 'No tip',
    'comment_hint': 'Comment (optional)',
    'thanks_rating': 'Thanks for your rating!',

    // Chat
    'chat_empty': 'Send a message to {name}',
    'type_message': 'Type a message…',
    'quick_coming': 'Coming now',
    'quick_where': 'Where exactly are you?',
    'quick_wait': 'Please wait 2 minutes',
    'quick_thanks': 'Thank you!',
    'no_chats': 'Chats with your driver appear here during a ride.',
    'your_driver': 'Your driver',
    'support_team': '{brand} team',
    'support_desc': 'Message us on WhatsApp, 7 days a week',

    // Bookings
    'active_ride': 'Current ride',
    'past_rides': 'Past rides',
    'no_rides': 'No rides yet.',
    'cancelled': 'Cancelled',
    'in_progress': 'In progress',
    'receipt': 'Receipt',
    'your_rating': 'Your rating',

    // Profile
    'payment_methods': 'Payment methods',
    'promo_code': 'Promo code',
    'enter_code': 'Enter code',
    'settings': 'Settings',
    'language': 'Language',
    'terms_privacy': 'Terms & Privacy',
    'legal_text':
        'By using the app you accept the terms of use. '
        'Your data is processed under Albanian personal data protection law.',
    'sign_out': 'Sign out',
    'tap_to_set': 'Tap to set',
    'become_driver': 'Become a driver',
    'become_driver_desc': 'Have a taxi? Start getting customers',
    'switch_to_passenger': 'Switch to passenger mode',

    // Driver
    'you_are_online': 'You are online',
    'you_are_offline': 'You are offline',
    'n_requests': '{n} requests',
    'go_online': 'Go online',
    'go_offline': 'Go offline',
    'go_online_title': 'Ready to work?',
    'go_online_desc': 'Go online to receive requests from passengers nearby.',
    'waiting_requests': 'Waiting for requests…',
    'waiting_requests_desc': 'New requests appear here automatically.',
    'request_meta': '{eta} to pickup · {km} trip, ~{min}',
    'offer_sent_waiting': 'Offer of {price} sent. Waiting for the passenger…',
    'accept_for': 'Accept for {price}',
    'passenger_chose_other': 'The passenger chose another driver',
    'go_to_pickup': 'Go to the pickup',
    'waiting_passenger': 'Waiting for the passenger',
    'drive_to_destination': 'Drive to the destination',
    'navigate': 'Navigate',
    'i_arrived': 'I have arrived',
    'start_trip': 'Start trip',
    'complete_trip': 'Complete trip',
    'trip_completed': 'Trip completed',
    'collect_cash': 'Collect {amount} in cash from the passenger.',
    'paid_by_card': '{amount} is paid by card.',
    'cancel_ride_q': 'Cancel this ride?',
    'cancel_ride_driver_warning': 'Frequent cancellations lower your rating.',
    'yes_cancel': 'Yes, cancel',
    'today': 'Today',
    'trips': 'Trips',
    'online_hours': 'Online hours',
    'avg_trip': 'Average',
    'last_7_days': 'Last 7 days',
    'zero_commission': 'No commission: every lek of the fare is yours.',
    'recent_trips': 'Recent trips',
    'no_trips_yet': 'No trips yet today.',
    'your_vehicle': 'Your vehicle',
    'add_vehicle': 'Add your vehicle',
    'vehicle_intro':
        'Passengers see the make, model and plate before they get in.',
    'make': 'Make',
    'model': 'Model',
    'plate': 'Plate number',
    'color': 'Colour',
    'service_type': 'Service type',
    'fill_all_fields': 'Please fill in make and model',
    'invalid_plate': 'Plate must look like AA 123 BB',
    'pending_approval': 'Your documents are being reviewed. You will be notified when your account is approved.',
    'documents': 'Documents',
    'doc_license': 'Driving licence',
    'doc_registration': 'Vehicle registration',
    'doc_taxi_permit': 'Taxi licence (Municipality)',
    'doc_insurance': 'Vehicle insurance',
    'doc_verified': 'Verified',
    'doc_send_office': 'Send it to the office or on WhatsApp',

    // Errors
    'err_generic': 'Something went wrong. Please try again.',
    'err_invalid_code': 'The code is incorrect',
    'err_otp_expired': 'The code has expired. Request a new one.',
    'err_over_sms_send_rate_limit':
        'Too many requests. Please wait before requesting another code.',
    'err_sms_send_failed': 'The SMS could not be sent. Check the number.',
    'err_request_closed': 'This request is no longer active',
    'err_offer_expired': 'The offer has expired',
    'err_passenger_chose_another': 'The passenger chose another driver',
    'err_vehicle_not_approved': 'Your vehicle has not been approved yet',
    'err_wrong_category': 'This request is for a different car type',
    'err_driver_offline': 'Go online to send offers',
    'err_subscription_expired':
        'Your subscription has expired. Please contact the office.',
    'err_price_too_low':
        'The price cannot be lower than the passenger\'s offer',
    'err_not_allowed': 'This action is not allowed',
    'err_driver_busy': 'The driver just took another ride',
    'err_cannot_cancel': 'The ride cannot be cancelled now',
    'err_invalid_transition': 'Invalid action for this ride',
  };
}
