// All user-facing text. `{name}` placeholders are filled by context.tr().

class Strings {
  static const byLang = {'sq': sq, 'en': en};

  static const sq = <String, String>{
    // General
    'continue': 'Vazhdo',
    'save': 'Ruaj',
    'cancel': 'Anulo',
    'ok': 'Në rregull',
    'no': 'Jo',
    'apply': 'Apliko',
    'skip': 'Kalo',
    'submit': 'Dërgo',
    'free': 'Falas',
    'decrease': 'Më pak',
    'increase': 'Më shumë',
    'locating': 'Po gjejmë vendndodhjen…',
    'current_location': 'Vendndodhja aktuale',
    'n_trips': '{n} qira',
    'n_seats': '{n} vende',
    'n_days': '{n} ditë',
    'per_day_short': '/ditë',
    'in_total': 'gjithsej',

    // Login
    'login_title': 'Mirë se vini!',
    'login_subtitle':
        'Shkruani numrin e telefonit. Do t\'ju dërgojmë një kod me SMS.',
    'login_terms': 'Duke vazhduar, pranoni Kushtet e Përdorimit dhe Politikën e Privatësisë.',
    'invalid_phone':
        'Shkruani një numër celulari të vlefshëm shqiptar (p.sh. 069 123 4567)',
    'demo_login_hint':
        'Version demo: shkruani çdo numër shqiptar dhe kodin {code}.',
    'otp_title': 'Shkruani kodin',
    'otp_subtitle': 'Kodi 6-shifror u dërgua në {phone}',
    'verify': 'Verifiko',
    'resend_in': 'Ridërgo kodin pas {s}s',
    'resend_code': 'Ridërgo kodin',
    'setup_title': 'Si quheni?',
    'setup_subtitle': 'Emri juaj u shfaqet pronarëve dhe qiramarrësve.',
    'full_name': 'Emri dhe mbiemri',
    'enter_name': 'Ju lutem shkruani emrin tuaj',
    'how_use_app': 'Çfarë dëshironi të bëni?',
    'role_renter': 'Gjej makinë me qira',
    'role_renter_desc': 'Merrni makinë me qira nga njerëz afër jush',
    'role_owner': 'Kam makinë për qira',
    'role_owner_desc': 'Jepeni makinën tuaj me qira dhe fitoni para',
    'get_started': 'Fillo',

    // Tabs
    'tab_search': 'Kërko',
    'tab_rentals': 'Qiratë e mia',
    'tab_chat': 'Biseda',
    'tab_profile': 'Profili',
    'tab_requests': 'Kërkesat',
    'tab_my_cars': 'Makinat',
    'tab_earnings': 'Fitimet',
    'tab_account': 'Llogaria',

    // Home & search
    'good_morning': 'Mirëmëngjes',
    'good_afternoon': 'Mirëdita',
    'good_evening': 'Mirëmbrëma',
    'home_subtitle': 'Çfarë makine ju duhet?',
    'where': 'Ku',
    'pickup': 'Marrja',
    'return': 'Kthimi',
    'all_cars': 'Të gjitha',
    'search_cars': 'Kërko makina',
    'cat_economy': 'Ekonomike',
    'cat_suv': 'SUV / 4x4',
    'cat_luxury': 'Luksoze',
    'cat_van': 'Furgon',
    'limited_offer': 'Ofertë e kufizuar',
    'promo_title': '{p}% zbritje për qiranë e parë',
    'promo_active': 'Kodi u aktivizua',
    'promo_applied': 'Zbritja {p}% u aplikua',
    'promo_invalid': 'Kodi nuk është i vlefshëm ose është përdorur',
    'cars_near': 'Makina afër: {place}',
    'no_cars_found': 'Nuk ka makina të lira për këto data këtu. Provoni data të tjera ose një vend tjetër.',
    'see_all_n': 'Shiko të gjitha ({n})',
    'home_place': 'Shtëpia',
    'work_place': 'Puna',
    'choose_dates': 'Zgjidhni datat',
    'pickup_time': 'Ora e marrjes dhe kthimit',
    'pickup_time_desc': 'Makina merret dhe kthehet në të njëjtën orë.',
    'change_dates': 'Ndrysho datat',
    'your_dates': 'Datat tuaja',
    'list_view': 'Listë',
    'map_view': 'Hartë',
    'automatic': 'Automatike',
    'manual': 'Manuale',
    'sort_distance': 'Më afër',
    'sort_priceLow': 'Më lirë',
    'sort_priceHigh': 'Më shtrenjtë',
    'sort_rating': 'Vlerësimi',
    'n_cars_available': '{n} makina të lira',

    // Where
    'where_to': 'Ku?',
    'where_need_car': 'Ku ju duhet makina?',
    'where_is_car': 'Ku ndodhet makina?',
    'delivery_address': 'Adresa e dorëzimit',
    'set_home': 'Adresa e shtëpisë',
    'set_work': 'Adresa e punës',
    'search_place': 'Kërkoni vend ose adresë',
    'use_current_location': 'Përdor vendndodhjen aktuale',
    'saved_places': 'Vendet e ruajtura',
    'recent': 'Së fundmi',
    'suggested': 'Të sugjeruara',
    'no_results': 'Asnjë rezultat. Provoni një emër tjetër.',

    // Car
    'fuel_petrol': 'Benzinë',
    'fuel_diesel': 'Naftë',
    'fuel_hybrid': 'Hibride',
    'fuel_electric': 'Elektrike',
    'free_delivery': 'Dorëzim falas',
    'delivery_for': 'Dorëzim {p}',
    'owner': 'Pronari',
    'renter': 'Qiramarrësi',
    'km_per_day': '{n} km/ditë',
    'pickup_location': 'Vendi i marrjes',
    'directions': 'Udhëzimet',
    'delivery_desc': 'Pronari mund ta sjellë makinën te ju për {p}.',
    'delivery_free_desc': 'Pronari mund ta sjellë makinën te ju falas.',
    'rental_terms': 'Kushtet e qirasë',
    'deposit': 'Depozita',
    'min_rental': 'Qiraja minimale',
    'mileage': 'Kilometrazhi',
    'fuel_policy': 'Karburanti',
    'fuel_policy_value': 'Kthehet me të njëjtin nivel',
    'requirements': 'Kërkesat',
    'requirements_value': 'Mbi 21 vjeç, patentë mbi 1 vit',
    'min_days_note': 'Kjo makinë jepet të paktën {n} ditë',
    'book_now': 'Rezervo',

    // Price
    'price': 'Çmimi',
    'long_stay_discount': 'Zbritje për qira të gjatë',
    'promo_discount': 'Kodi promocional',
    'delivery': 'Dorëzimi',
    'total': 'Totali',
    'deposit_refundable': 'Depozitë (kthehet)',
    'payment': 'Pagesa',

    // Booking flow
    'step_dates': 'Datat',
    'step_payment': 'Pagesa',
    'step_offer': 'Oferta',
    'when_need_car': 'Kur ju duhet makina?',
    'how_get_car': 'Si do ta merrni makinën?',
    'pickup_at_owner': 'E marr vetë',
    'delivery_to_me': 'Ma sillni te unë',
    'enter_delivery_address': 'Zgjidhni adresën e dorëzimit',
    'how_pay': 'Si dëshironi të paguani?',
    'charged_after': 'Paguani vetëm kur të merrni makinën.',
    'pay_cash': 'Para në dorë',
    'pay_cash_desc': 'Paguani pronarin kur merrni makinën',
    'pay_card': 'Kartë',
    'cards': 'Kartat',
    'add_card': 'Shto kartë',
    'digital_wallets': 'Portofole dixhitale',
    'confirm_face_id': 'Konfirmo me Face ID',
    'confirm_google': 'Konfirmo me Google',
    'paying_with': 'Paguani me',
    'pay_with': 'Pagesa',
    'card_number': 'Numri i kartës',
    'card_invalid': 'Numri i kartës nuk është i saktë',
    'expiry_invalid': 'Data e skadencës duhet të jetë MM/VV',
    'card_expired': 'Kjo kartë ka skaduar',
    'cvc_invalid': 'Kodi CVC nuk është i saktë',
    'card_secure': 'Në telefon ruhen vetëm 4 shifrat e fundit të kartës.',
    'your_offer_title': 'Oferta juaj',
    'your_offer_desc': 'Mund të ofroni më pak se çmimi i pronarit. Pronari e pranon, e refuzon ose ju bën një kundërofertë.',
    'price_per_day': 'Çmimi për ditë',
    'below_listed': 'Më pak se {p} që kërkon pronari',
    'listed_price': 'Çmimi i pronarit: pranohet më shpejt',
    'note_to_owner': 'Mesazh për pronarin (opsional)',
    'request_info':
        'Nuk paguani asgjë tani. Rezervimi konfirmohet kur pronari pranon.',
    'send_request': 'Dërgo kërkesën',

    // Booking screen
    'message': 'Mesazh',
    'call': 'Telefono',
    'cancel_why': 'Pse po e anuloni?',
    'reason_changed_plans': 'Ndryshova planet',
    'reason_found_other': 'Gjeta makinë tjetër',
    'reason_price': 'Çmimi është shumë i lartë',
    'reason_car_unavailable': 'Makina nuk është më e lirë',
    'reason_other': 'Tjetër',
    'cannot_call': 'Telefonata nuk mund të kryhet nga kjo pajisje',
    'cancel_request': 'Anulo kërkesën',
    'cancel_booking': 'Anulo rezervimin',
    'accept': 'Prano',
    'decline': 'Refuzo',
    'counter_offer': 'Bëj kundërofertë',
    'counter_short': 'Kundërofertë',
    'counter_desc': 'Qiramarrësi ofron {offer} në ditë. Zgjidhni çmimin tuaj.',
    'send_counter': 'Dërgo kundërofertën',
    'counter_sent': 'Kundëroferta u dërgua',
    'booking_confirmed': 'Rezervimi u konfirmua',
    'st_requested_title': 'Kërkesa u dërgua',
    'st_requested_body': 'Po presim përgjigjen e {name}. Zakonisht përgjigjen brenda pak minutash.',
    'st_new_request_title': 'Kërkesë e re nga {name}',
    'st_new_request_body': 'Ofron {offer} në ditë (ju kërkoni {listed}).',
    'st_countered_title': '{name} ju bën një kundërofertë',
    'st_countered_body': '{price} në ditë në vend të {offer}. Pranojeni për ta konfirmuar rezervimin.',
    'st_counter_sent_title': 'Kundëroferta u dërgua',
    'st_counter_sent_body': 'Po presim që {name} të pranojë {price} në ditë.',
    'st_confirmed_title': 'Rezervimi u konfirmua!',
    'st_confirmed_body': 'Takohuni me {name} më {when}. Merrni me vete patentën dhe kartën e identitetit. Depozita: {deposit}.',
    'st_owner_confirmed_title': 'Rezervim i konfirmuar',
    'st_owner_confirmed_body': 'Dorëzojani makinën {name} më {when}. Kontrolloni patentën dhe merrni depozitën.',
    'st_active_title': 'Makina është te ju',
    'st_active_body': 'Kthejeni deri më {when} me të njëjtin nivel karburanti. Udhëtim të mbarë!',
    'st_owner_active_title': 'Makina është te {name}',
    'st_owner_active_body': 'Duhet të kthehet më {when}.',
    'st_completed_title': 'Qiraja përfundoi',
    'st_rate_body': 'Si ishte makina dhe {name}?',
    'st_owner_completed_body': 'Fituat {total} nga kjo qira.',
    'st_declined_body': 'Pronari nuk mund ta japë makinën për këto data. Provoni një makinë tjetër.',
    'st_owner_declined_body': 'E refuzuat këtë kërkesë.',
    'st_cancelled_body': 'Ky rezervim u anulua.',
    'st_counter_declined_body': '{name} nuk e pranoi kundërofertën.',
    'st_expired_body': 'Kërkesa skadoi pa përgjigje.',
    'i_picked_up': 'Mora makinën',
    'i_handed_over': 'Ia dorëzova makinën',
    'i_returned': 'E ktheva makinën',
    'car_returned': 'Makina u kthye',
    'find_another_car': 'Gjej makinë tjetër',
    'submit_review': 'Dërgo vlerësimin',
    'comment_hint': 'Koment (opsional)',
    'thanks_rating': 'Faleminderit për vlerësimin!',
    'status_requested': 'Në pritje',
    'status_countered': 'Kundërofertë',
    'status_confirmed': 'Konfirmuar',
    'status_active': 'Në përdorim',
    'status_completed': 'Përfunduar',
    'status_declined': 'Refuzuar',
    'status_cancelled': 'Anuluar',
    'status_expired': 'Skaduar',

    // Chat
    'chat_empty': 'Dërgoni një mesazh te {name}',
    'type_message': 'Shkruani një mesazh…',
    'quick_coming': 'Po vij tani',
    'quick_where': 'Ku ndodheni saktësisht?',
    'quick_wait': 'Do vonohem pak, ju lutem më prisni',
    'quick_thanks': 'Faleminderit!',
    'no_chats': 'Bisedat me pronarët shfaqen këtu pasi të dërgoni një kërkesë.',
    'no_chats_owner':
        'Bisedat me qiramarrësit shfaqen këtu kur të merrni kërkesa.',
    'conversations': 'Bisedat',
    'support': 'Ndihma',
    'support_team': 'Ekipi i {brand}',
    'support_desc': 'Na shkruani në WhatsApp, 7 ditë në javë',

    // Rentals
    'no_rentals': 'Ende nuk keni marrë makinë me qira.',
    'current_rentals': 'Aktuale dhe të ardhshme',
    'waiting_answer': 'Në pritje të përgjigjes',
    'past_rentals': 'Të mëparshme',

    // Profile
    'payment_methods': 'Mënyrat e pagesës',
    'promo_code': 'Kodi promocional',
    'enter_code': 'Shkruani kodin',
    'settings': 'Cilësimet',
    'language': 'Gjuha',
    'terms_privacy': 'Kushtet & Privatësia',
    'legal_text':
        'Duke përdorur aplikacionin pranoni kushtet e përdorimit. '
        'Të dhënat tuaja përpunohen sipas ligjit shqiptar për mbrojtjen e të dhënave personale.',
    'sign_out': 'Dilni',
    'tap_to_set': 'Prekni për ta vendosur',
    'become_owner': 'Kam makinë për qira',
    'become_owner_desc': 'Jepeni makinën tuaj me qira dhe fitoni',
    'switch_to_renter': 'Gjej makinë me qira',
    'safety': 'Siguria',
    'emergency': 'Emergjenca',
    'police': 'Policia',
    'ambulance': 'Ambulanca',

    // Owner
    'no_cars_title': 'Shtoni makinën tuaj të parë',
    'no_cars_body':
        'Publikoni makinën me çmimin tuaj dhe filloni të merrni kërkesa.',
    'add_car': 'Shto makinë',
    'edit_car': 'Ndrysho makinën',
    'no_requests_yet':
        'Ende nuk ka kërkesa. Kërkesat e reja shfaqen këtu automatikisht.',
    'new_requests': 'Kërkesa të reja',
    'waiting_renter': 'Në pritje të qiramarrësit',
    'upcoming_handovers': 'Dorëzimet e ardhshme',
    'cars_out': 'Makina me qira tani',
    'history': 'Historiku',
    'you_ask': 'ju kërkoni {p}',
    'my_cars_desc': 'Fshihni një makinë kur nuk është e lirë; mund ta shfaqni sërish kur të doni.',
    'approval_note': 'Makinat e reja shfaqen pasi verifikojmë lejen e qarkullimit dhe siguracionin.',
    'listed': 'E dukshme',
    'hidden': 'E fshehur',
    'car_added': 'Makina u publikua',
    'car_saved': 'Ndryshimet u ruajtën',
    'car_details': 'Të dhënat e makinës',
    'make': 'Marka',
    'model': 'Modeli',
    'year': 'Viti',
    'plate': 'Targa',
    'car_type': 'Lloji',
    'seats': 'Vende',
    'price_and_rules': 'Çmimi dhe rregullat',
    'suggested_price': 'Çmim i sugjeruar: {p}',
    'offer_delivery': 'Ofroj dorëzim',
    'offer_delivery_desc': 'E çoj makinën te klienti (p.sh. në aeroport)',
    'delivery_fee': 'Tarifa e dorëzimit',
    'description': 'Përshkrimi',
    'description_hint':
        'P.sh. Makinë e mirëmbajtur, e pastër, ideale për udhëtime në jug.',
    'publish_car': 'Publiko makinën',
    'choose_car_location': 'Zgjidhni ku ndodhet makina',
    'fill_make_model': 'Plotësoni markën dhe modelin',
    'invalid_year': 'Shkruani një vit të saktë',
    'invalid_plate': 'Targa duhet të jetë si AA 123 BB',
    'color_white': 'E bardhë',
    'color_black': 'E zezë',
    'color_silver': 'Argjendi',
    'color_grey': 'Gri',
    'color_blue': 'Blu',
    'color_red': 'E kuqe',
    'color_green': 'Jeshile',
    'color_yellow': 'E verdhë',
    'color_brown': 'Kafe',
    'this_month': 'Këtë muaj',
    'rentals': 'Qira',
    'days_rented': 'Ditë',
    'avg_per_day': 'Mesatarja/ditë',
    'all_time': 'Gjithsej që nga fillimi',
    'completed_rentals': 'Qiratë e përfunduara',
    'no_completed_rentals': 'Ende nuk keni qira të përfunduara.',
    'documents': 'Dokumentet',
    'doc_registration': 'Leja e qarkullimit',
    'doc_insurance': 'Siguracioni i makinës',
    'doc_id': 'Karta e identitetit',
    'doc_send_office': 'Dërgojeni në zyrë ose në WhatsApp',

    // Errors
    'err_generic': 'Diçka shkoi keq. Provoni përsëri.',
    'err_invalid_code': 'Kodi është i gabuar',
    'err_otp_expired': 'Kodi ka skaduar. Kërkoni një kod të ri.',
    'err_over_sms_send_rate_limit':
        'Shumë kërkesa. Prisni pak para se të kërkoni kod tjetër.',
    'err_sms_send_failed': 'SMS nuk u dërgua. Kontrolloni numrin.',
    'err_car_unavailable': 'Makina nuk është më e lirë për këto data',
    'err_offer_too_low': 'Oferta është shumë e ulët për këtë makinë',
    'err_min_days': 'Rezervimi është më i shkurtër se minimumi i pronarit',
    'err_own_car': 'Nuk mund të rezervoni makinën tuaj',
    'err_invalid_dates': 'Datat nuk janë të sakta',
    'err_not_allowed': 'Ky veprim nuk lejohet',
    'err_not_found': 'Rezervimi nuk u gjet',
    'err_cannot_cancel': 'Rezervimi nuk mund të anulohet tani',
    'err_invalid_transition': 'Veprim i pavlefshëm për këtë rezervim',
    'err_counter_too_low':
        'Kundëroferta duhet të jetë më e lartë se oferta e qiramarrësit',
    'err_request_expired': 'Kërkesa ka skaduar',
  };

  static const en = <String, String>{
    // General
    'continue': 'Continue',
    'save': 'Save',
    'cancel': 'Cancel',
    'ok': 'OK',
    'no': 'No',
    'apply': 'Apply',
    'skip': 'Skip',
    'submit': 'Submit',
    'free': 'Free',
    'decrease': 'Decrease',
    'increase': 'Increase',
    'locating': 'Finding your location…',
    'current_location': 'Current location',
    'n_trips': '{n} rentals',
    'n_seats': '{n} seats',
    'n_days': '{n} days',
    'per_day_short': '/day',
    'in_total': 'in total',

    // Login
    'login_title': 'Welcome!',
    'login_subtitle': 'Enter your phone number. We will text you a code.',
    'login_terms':
        'By continuing you accept the Terms of Use and Privacy Policy.',
    'invalid_phone': 'Enter a valid Albanian mobile number (e.g. 069 123 4567)',
    'demo_login_hint':
        'Demo version: enter any Albanian number and the code {code}.',
    'otp_title': 'Enter the code',
    'otp_subtitle': 'We sent a 6-digit code to {phone}',
    'verify': 'Verify',
    'resend_in': 'Resend code in {s}s',
    'resend_code': 'Resend code',
    'setup_title': 'What is your name?',
    'setup_subtitle': 'Your name is shown to car owners and renters.',
    'full_name': 'Full name',
    'enter_name': 'Please enter your name',
    'how_use_app': 'What would you like to do?',
    'role_renter': 'Find a car to rent',
    'role_renter_desc': 'Rent a car from people near you',
    'role_owner': 'I have a car for rent',
    'role_owner_desc': 'Rent out your car and earn money',
    'get_started': 'Get started',

    // Tabs
    'tab_search': 'Search',
    'tab_rentals': 'My rentals',
    'tab_chat': 'Chat',
    'tab_profile': 'Profile',
    'tab_requests': 'Requests',
    'tab_my_cars': 'My cars',
    'tab_earnings': 'Earnings',
    'tab_account': 'Account',

    // Home & search
    'good_morning': 'Good morning',
    'good_afternoon': 'Good afternoon',
    'good_evening': 'Good evening',
    'home_subtitle': 'What car do you need?',
    'where': 'Where',
    'pickup': 'Pick-up',
    'return': 'Return',
    'all_cars': 'All',
    'search_cars': 'Search cars',
    'cat_economy': 'Economy',
    'cat_suv': 'SUV / 4x4',
    'cat_luxury': 'Luxury',
    'cat_van': 'Van',
    'limited_offer': 'Limited offer',
    'promo_title': '{p}% off your first rental',
    'promo_active': 'Code applied',
    'promo_applied': '{p}% discount applied',
    'promo_invalid': 'This code is invalid or already used',
    'cars_near': 'Cars near {place}',
    'no_cars_found': 'No cars are free here for these dates. Try other dates or another place.',
    'see_all_n': 'See all ({n})',
    'home_place': 'Home',
    'work_place': 'Work',
    'choose_dates': 'Choose dates',
    'pickup_time': 'Pick-up and return time',
    'pickup_time_desc':
        'The car is picked up and returned at the same time of day.',
    'change_dates': 'Change dates',
    'your_dates': 'Your dates',
    'list_view': 'List',
    'map_view': 'Map',
    'automatic': 'Automatic',
    'manual': 'Manual',
    'sort_distance': 'Nearest',
    'sort_priceLow': 'Cheapest',
    'sort_priceHigh': 'Most expensive',
    'sort_rating': 'Rating',
    'n_cars_available': '{n} cars available',

    // Where
    'where_to': 'Where?',
    'where_need_car': 'Where do you need the car?',
    'where_is_car': 'Where is the car parked?',
    'delivery_address': 'Delivery address',
    'set_home': 'Home address',
    'set_work': 'Work address',
    'search_place': 'Search a place or address',
    'use_current_location': 'Use current location',
    'saved_places': 'Saved places',
    'recent': 'Recent',
    'suggested': 'Suggested',
    'no_results': 'No results. Try another name.',

    // Car
    'fuel_petrol': 'Petrol',
    'fuel_diesel': 'Diesel',
    'fuel_hybrid': 'Hybrid',
    'fuel_electric': 'Electric',
    'free_delivery': 'Free delivery',
    'delivery_for': 'Delivery {p}',
    'owner': 'Owner',
    'renter': 'Renter',
    'km_per_day': '{n} km/day',
    'pickup_location': 'Pick-up location',
    'directions': 'Directions',
    'delivery_desc': 'The owner can bring the car to you for {p}.',
    'delivery_free_desc': 'The owner can bring the car to you for free.',
    'rental_terms': 'Rental terms',
    'deposit': 'Deposit',
    'min_rental': 'Minimum rental',
    'mileage': 'Mileage',
    'fuel_policy': 'Fuel',
    'fuel_policy_value': 'Return at the same level',
    'requirements': 'Requirements',
    'requirements_value': 'Over 21, licence held 1+ year',
    'min_days_note': 'This car is rented for at least {n} days',
    'book_now': 'Book',

    // Price
    'price': 'Price',
    'long_stay_discount': 'Long rental discount',
    'promo_discount': 'Promo code',
    'delivery': 'Delivery',
    'total': 'Total',
    'deposit_refundable': 'Deposit (refunded)',
    'payment': 'Payment',

    // Booking flow
    'step_dates': 'Dates',
    'step_payment': 'Payment',
    'step_offer': 'Offer',
    'when_need_car': 'When do you need the car?',
    'how_get_car': 'How will you get the car?',
    'pickup_at_owner': 'I will pick it up',
    'delivery_to_me': 'Deliver it to me',
    'enter_delivery_address': 'Choose the delivery address',
    'how_pay': 'How would you like to pay?',
    'charged_after': 'You only pay when you pick up the car.',
    'pay_cash': 'Cash',
    'pay_cash_desc': 'Pay the owner when you pick up the car',
    'pay_card': 'Card',
    'cards': 'Cards',
    'add_card': 'Add card',
    'digital_wallets': 'Digital wallets',
    'confirm_face_id': 'Confirm with Face ID',
    'confirm_google': 'Confirm with Google',
    'paying_with': 'Paying with',
    'pay_with': 'Pay with',
    'card_number': 'Card number',
    'card_invalid': 'The card number is not valid',
    'expiry_invalid': 'Expiry must be MM/YY',
    'card_expired': 'This card has expired',
    'cvc_invalid': 'The CVC is not valid',
    'card_secure':
        'Only the last 4 digits of the card are stored on the phone.',
    'your_offer_title': 'Your offer',
    'your_offer_desc': 'You can offer less than the owner\'s price. The owner accepts, declines or sends you a counter-offer.',
    'price_per_day': 'Price per day',
    'below_listed': 'Below the owner\'s {p}',
    'listed_price': 'Owner\'s price: accepted faster',
    'note_to_owner': 'Message to the owner (optional)',
    'request_info':
        'You pay nothing now. The booking is confirmed when the owner accepts.',
    'send_request': 'Send request',

    // Booking screen
    'message': 'Message',
    'call': 'Call',
    'cancel_why': 'Why are you cancelling?',
    'reason_changed_plans': 'My plans changed',
    'reason_found_other': 'I found another car',
    'reason_price': 'The price is too high',
    'reason_car_unavailable': 'The car is no longer available',
    'reason_other': 'Other',
    'cannot_call': 'Calls are not available on this device',
    'cancel_request': 'Cancel request',
    'cancel_booking': 'Cancel booking',
    'accept': 'Accept',
    'decline': 'Decline',
    'counter_offer': 'Make a counter-offer',
    'counter_short': 'Counter',
    'counter_desc': 'The renter offers {offer} per day. Choose your price.',
    'send_counter': 'Send counter-offer',
    'counter_sent': 'Counter-offer sent',
    'booking_confirmed': 'Booking confirmed',
    'st_requested_title': 'Request sent',
    'st_requested_body':
        'Waiting for {name} to answer. Owners usually reply within minutes.',
    'st_new_request_title': 'New request from {name}',
    'st_new_request_body': 'Offers {offer} per day (you ask {listed}).',
    'st_countered_title': '{name} sent you a counter-offer',
    'st_countered_body':
        '{price} per day instead of {offer}. Accept it to confirm the booking.',
    'st_counter_sent_title': 'Counter-offer sent',
    'st_counter_sent_body': 'Waiting for {name} to accept {price} per day.',
    'st_confirmed_title': 'Booking confirmed!',
    'st_confirmed_body': 'Meet {name} on {when}. Bring your driving licence and ID card. Deposit: {deposit}.',
    'st_owner_confirmed_title': 'Confirmed booking',
    'st_owner_confirmed_body': 'Hand the car to {name} on {when}. Check the licence and take the deposit.',
    'st_active_title': 'You have the car',
    'st_active_body':
        'Return it by {when} with the same fuel level. Have a good trip!',
    'st_owner_active_title': '{name} has the car',
    'st_owner_active_body': 'Due back on {when}.',
    'st_completed_title': 'Rental finished',
    'st_rate_body': 'How were the car and {name}?',
    'st_owner_completed_body': 'You earned {total} from this rental.',
    'st_declined_body':
        'The owner cannot rent the car for these dates. Try another car.',
    'st_owner_declined_body': 'You declined this request.',
    'st_cancelled_body': 'This booking was cancelled.',
    'st_counter_declined_body': '{name} did not accept the counter-offer.',
    'st_expired_body': 'The request expired without an answer.',
    'i_picked_up': 'I picked up the car',
    'i_handed_over': 'I handed over the car',
    'i_returned': 'I returned the car',
    'car_returned': 'The car is back',
    'find_another_car': 'Find another car',
    'submit_review': 'Submit review',
    'comment_hint': 'Comment (optional)',
    'thanks_rating': 'Thanks for your review!',
    'status_requested': 'Pending',
    'status_countered': 'Counter-offer',
    'status_confirmed': 'Confirmed',
    'status_active': 'In use',
    'status_completed': 'Completed',
    'status_declined': 'Declined',
    'status_cancelled': 'Cancelled',
    'status_expired': 'Expired',

    // Chat
    'chat_empty': 'Send a message to {name}',
    'type_message': 'Type a message…',
    'quick_coming': 'On my way',
    'quick_where': 'Where exactly are you?',
    'quick_wait': 'I will be a bit late, please wait',
    'quick_thanks': 'Thank you!',
    'no_chats': 'Chats with owners appear here after you send a request.',
    'no_chats_owner': 'Chats with renters appear here when you get requests.',
    'conversations': 'Conversations',
    'support': 'Support',
    'support_team': '{brand} team',
    'support_desc': 'Message us on WhatsApp, 7 days a week',

    // Rentals
    'no_rentals': 'You have not rented a car yet.',
    'current_rentals': 'Current and upcoming',
    'waiting_answer': 'Waiting for an answer',
    'past_rentals': 'Past',

    // Profile
    'payment_methods': 'Payment methods',
    'promo_code': 'Promo code',
    'enter_code': 'Enter code',
    'settings': 'Settings',
    'language': 'Language',
    'terms_privacy': 'Terms & Privacy',
    'legal_text':
        'By using the app you accept the terms of use. '
        'Your data is processed under Albanian personal data protection law.',
    'sign_out': 'Sign out',
    'tap_to_set': 'Tap to set',
    'become_owner': 'I have a car for rent',
    'become_owner_desc': 'Rent out your car and earn',
    'switch_to_renter': 'Find a car to rent',
    'safety': 'Safety',
    'emergency': 'Emergency',
    'police': 'Police',
    'ambulance': 'Ambulance',

    // Owner
    'no_cars_title': 'Add your first car',
    'no_cars_body':
        'List your car at your own price and start getting requests.',
    'add_car': 'Add car',
    'edit_car': 'Edit car',
    'no_requests_yet':
        'No requests yet. New requests appear here automatically.',
    'new_requests': 'New requests',
    'waiting_renter': 'Waiting for the renter',
    'upcoming_handovers': 'Upcoming handovers',
    'cars_out': 'Rented out now',
    'history': 'History',
    'you_ask': 'you ask {p}',
    'my_cars_desc':
        'Hide a car when it is not available; show it again whenever you like.',
    'approval_note':
        'New cars appear after we verify the registration and insurance.',
    'listed': 'Visible',
    'hidden': 'Hidden',
    'car_added': 'Car published',
    'car_saved': 'Changes saved',
    'car_details': 'Car details',
    'make': 'Make',
    'model': 'Model',
    'year': 'Year',
    'plate': 'Plate number',
    'car_type': 'Type',
    'seats': 'Seats',
    'price_and_rules': 'Price and rules',
    'suggested_price': 'Suggested price: {p}',
    'offer_delivery': 'I offer delivery',
    'offer_delivery_desc': 'I bring the car to the customer (e.g. the airport)',
    'delivery_fee': 'Delivery fee',
    'description': 'Description',
    'description_hint':
        'E.g. Well kept, clean car, ideal for trips to the south.',
    'publish_car': 'Publish car',
    'choose_car_location': 'Choose where the car is parked',
    'fill_make_model': 'Please fill in make and model',
    'invalid_year': 'Enter a valid year',
    'invalid_plate': 'Plate must look like AA 123 BB',
    'color_white': 'White',
    'color_black': 'Black',
    'color_silver': 'Silver',
    'color_grey': 'Grey',
    'color_blue': 'Blue',
    'color_red': 'Red',
    'color_green': 'Green',
    'color_yellow': 'Yellow',
    'color_brown': 'Brown',
    'this_month': 'This month',
    'rentals': 'Rentals',
    'days_rented': 'Days',
    'avg_per_day': 'Avg / day',
    'all_time': 'All time',
    'completed_rentals': 'Completed rentals',
    'no_completed_rentals': 'No completed rentals yet.',
    'documents': 'Documents',
    'doc_registration': 'Vehicle registration',
    'doc_insurance': 'Vehicle insurance',
    'doc_id': 'ID card',
    'doc_send_office': 'Send it to the office or on WhatsApp',

    // Errors
    'err_generic': 'Something went wrong. Please try again.',
    'err_invalid_code': 'The code is incorrect',
    'err_otp_expired': 'The code has expired. Request a new one.',
    'err_over_sms_send_rate_limit':
        'Too many requests. Please wait before requesting another code.',
    'err_sms_send_failed': 'The SMS could not be sent. Check the number.',
    'err_car_unavailable': 'The car is no longer free for these dates',
    'err_offer_too_low': 'The offer is too low for this car',
    'err_min_days': 'The booking is shorter than the owner\'s minimum',
    'err_own_car': 'You cannot book your own car',
    'err_invalid_dates': 'The dates are not valid',
    'err_not_allowed': 'This action is not allowed',
    'err_not_found': 'Booking not found',
    'err_cannot_cancel': 'The booking cannot be cancelled now',
    'err_invalid_transition': 'Invalid action for this booking',
    'err_counter_too_low':
        'The counter-offer must be higher than the renter\'s offer',
    'err_request_expired': 'The request has expired',
  };
}
